version: '3.2'
services:
  app:
    build: .
    environment:
      - HOST=db
  grafana:
    image: "grafana/grafana"
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
   